// This file is auto-generated by @hey-api/openapi-ts

export const $UserKickOutListRequest = {
  type: 'object',
  properties: {
    userIds: {
      type: 'array',
      description: '학번 리스트',
      example: ['202412347', '202412349'],
      items: {
        type: 'string',
        pattern: '\\d{9}',
      },
    },
  },
  required: ['userIds'],
} as const

export const $ProfessorRequest = {
  type: 'object',
  description: '교수 수정 request 객체 입니다.',
  properties: {
    name: {
      type: 'string',
      description: '교수 이름',
      example: '이은정',
    },
    role: {
      type: 'string',
      description: '직위',
      example: '조교수',
    },
    contact: {
      type: 'string',
      description: '연락처',
      example: '031-249-9671',
      pattern: '^\\d{2,4}-\\d{3,4}-\\d{4}$',
    },
    email: {
      type: 'string',
      description: '이메일',
      example: 'ejlee@kyonggi.ac.kr',
      pattern: '^[A-Za-z0-9._%+-]+@(kyonggi|kgu)\\.ac\\.kr$',
    },
    img: {
      type: 'string',
      description: '이미지 URL',
      example: 'https://image.com/professor/profile/image',
      pattern: '^https?://.*$',
    },
    officeLoc: {
      type: 'string',
      description: '연구실 위치',
      example: '8213호',
    },
  },
  required: ['contact', 'email', 'img', 'name', 'officeLoc', 'role'],
} as const

export const $ProfessorPersistResponse = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      format: 'int64',
      description: '교수 id',
      example: 1,
    },
  },
  required: ['id'],
} as const

export const $PostCreateRequest = {
  type: 'object',
  description: '게시글 생성 request 객체 입니다.',
  properties: {
    title: {
      type: 'string',
      description: '게시물 제목',
      example: 'SW 부트캠프 4기 교육생 모집',
      maxLength: 100,
      minLength: 0,
    },
    content: {
      type: 'string',
      description: '게시물 내용',
      example: `SW 부트캠프 4기 교육생 모집
SW전문인재양성사업단에서는 SW부트캠프 4기 교육생을 모집합니다.
관심있는 학생들의 많은 신청 바랍니다.
- 모집기간 : 2024.10.07(월)~10.15(화)
- 신청방법 :https://kebkyonggi.quv.kr/68
`,
    },
    category: {
      type: 'string',
      description: '게시물 카테고리',
      enum: ['NOTIFICATION', 'NEWS'],
      example: 'NOTIFICATION',
    },
    isPinned: {
      type: 'boolean',
      description: '게시글 고정 여부',
      example: 'FALSE',
    },
  },
  required: ['content', 'isPinned', 'title'],
} as const

export const $PostPersistResponse = {
  type: 'object',
  properties: {
    postId: {
      type: 'integer',
      format: 'int64',
      description: '게시글 id',
      example: 1,
    },
  },
  required: ['postId'],
} as const

export const $LabCreateRequest = {
  type: 'object',
  description: '연구실 생성 request 객체 입니다.',
  properties: {
    name: {
      type: 'string',
      description: '연구실 이름',
      example: '인공지능연구실',
      maxLength: 15,
      minLength: 0,
    },
    loc: {
      type: 'string',
      description: '연구실 위치',
      example: '8502, 8503',
      maxLength: 10,
      minLength: 0,
    },
    site: {
      type: 'string',
      description: '연구실 홈페이지',
      example: 'http://ailab.kyonggi.ac.kr',
      pattern: '^(http|https)://[a-zA-Z0-9.-]+\\.kyonggi\\.ac\\.kr$',
    },
    advisor: {
      type: 'string',
      description: '연구실 담당교수',
      example: '박민준',
      maxLength: 15,
      minLength: 0,
    },
  },
  required: ['advisor', 'loc', 'name', 'site'],
} as const

export const $LabPersistResponse = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      format: 'int64',
      description: '연구실 id',
      example: 1,
    },
  },
  required: ['id'],
} as const

export const $FilePathResponse = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      format: 'int64',
      description: '파일 id',
      example: 1,
    },
    physicalPath: {
      type: 'string',
      description: '파일 경로',
      example: '/files/2025-curriculum',
    },
  },
  required: ['id', 'physicalPath'],
} as const

export const $ClubCreateRequest = {
  type: 'object',
  description: '동아리 생성 request 객체 입니다.',
  properties: {
    name: {
      type: 'string',
      description: '동아리 이름',
      example: 'C-Lab',
      maxLength: 15,
      minLength: 0,
    },
    description: {
      type: 'string',
      description: '동아리 설명',
      example: '경기대학교 AI컴퓨터공학부 개발동아리입니다.',
      maxLength: 50,
      minLength: 0,
    },
    site: {
      type: 'string',
      description: '동아리 홈페이지',
      example: 'https://www.clab.page/',
      pattern: '^(http|https)://.*$',
    },
  },
  required: ['description', 'name'],
} as const

export const $ClubPersistResponse = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      format: 'int64',
      description: '동아리 id',
      example: 1,
    },
  },
  required: ['id'],
} as const

export const $CarouselRequest = {
  type: 'object',
  description: '캐러셀 생성 request 객체 입니다.',
  properties: {
    text: {
      type: 'string',
      description: '캐러셀 설명',
      example: '경기대학교 AI컴퓨터공학부 메인 이미지',
      maxLength: 255,
      minLength: 0,
    },
    link: {
      type: 'string',
      description: '캐러셀 이미지 링크',
      example: 'https://www.kgu.ac.kr/',
    },
  },
} as const

export const $CarouselPersistResponse = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      format: 'int64',
      description: '캐러셀 ID',
      example: 1,
    },
  },
  required: ['id'],
} as const

export const $AboutCreateRequest = {
  type: 'object',
  description: '소개글 생성 request 객체 입니다.',
  properties: {
    category: {
      type: 'string',
      description: '카테고리',
      enum: ['DEPT_INTRO', 'DIRECTIONS'],
      example: 'DEPT_INTRO',
    },
    content: {
      type: 'string',
      description: '페이지 내용(JSON 형식)',
      example: '{key:value}',
    },
  },
  required: ['category', 'content'],
} as const

export const $AboutPersistResponse = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      format: 'int64',
      description: '소개글 id',
      example: 1,
    },
  },
  required: ['id'],
} as const

export const $PostUpdateRequest = {
  type: 'object',
  description: '게시글 수정 request 객체 입니다.',
  properties: {
    title: {
      type: 'string',
      description: '게시물 제목',
      example: 'SW 부트캠프 4기 교육생 모집',
      maxLength: 100,
      minLength: 0,
    },
    content: {
      type: 'string',
      description: '게시물 내용',
      example: `SW 부트캠프 4기 교육생 모집
SW전문인재양성사업단에서는 SW부트캠프 4기 교육생을 모집합니다.
관심있는 학생들의 많은 신청 바랍니다.
- 모집기간 : 2024.10.07(월)~10.15(화)
- 신청방법 :https://kebkyonggi.quv.kr/68
`,
    },
    category: {
      type: 'string',
      description: '게시물 카테고리',
      enum: ['NOTIFICATION', 'NEWS'],
      example: 'NOTIFICATION',
    },
    fileId: {
      type: 'integer',
      format: 'int64',
      description: '파일 ID',
      example: 1,
    },
    isPinned: {
      type: 'boolean',
      description: '게시글 고정 여부',
      example: 'FALSE',
    },
  },
  required: ['content', 'isPinned', 'title'],
} as const

export const $LabUpdateRequest = {
  type: 'object',
  description: '연구실 수정 request 객체 입니다.',
  properties: {
    name: {
      type: 'string',
      description: '연구실 이름',
      example: '인공지능연구실',
      maxLength: 15,
      minLength: 0,
    },
    loc: {
      type: 'string',
      description: '연구실 위치',
      example: '8502, 8503',
      maxLength: 10,
      minLength: 0,
    },
    site: {
      type: 'string',
      description: '연구실 홈페이지',
      example: 'http://ailab.kyonggi.ac.kr',
      pattern: '^(http|https)://[a-zA-Z0-9.-]+\\.kyonggi\\.ac\\.kr$',
    },
    advisor: {
      type: 'string',
      description: '연구실 담당교수',
      example: '박민준',
      maxLength: 15,
      minLength: 0,
    },
    fileId: {
      type: 'integer',
      format: 'int64',
      description: '파일 ID',
      example: 1,
    },
  },
  required: ['advisor', 'loc', 'name', 'site'],
} as const

export const $ClubUpdateRequest = {
  type: 'object',
  description: '동아리 수정 request 객체 입니다.',
  properties: {
    name: {
      type: 'string',
      description: '동아리 이름',
      example: 'C-Lab',
      maxLength: 15,
      minLength: 0,
    },
    description: {
      type: 'string',
      description: '동아리 설명',
      example: '경기대학교 AI컴퓨터공학부 개발동아리입니다.',
      maxLength: 50,
      minLength: 0,
    },
    site: {
      type: 'string',
      description: '동아리 홈페이지',
      example: 'https://www.clab.page/',
      pattern: '^(http|https)://.*$',
    },
    fileId: {
      type: 'integer',
      format: 'int64',
      description: '파일 ID',
      example: 1,
    },
  },
  required: ['description', 'name'],
} as const

export const $CarouselUpdateRequest = {
  type: 'object',
  description: '캐러셀 생성 request 객체 입니다.',
  properties: {
    text: {
      type: 'string',
      description: '캐러셀 설명',
      example: '경기대학교 AI컴퓨터공학부 메인 이미지',
      maxLength: 255,
      minLength: 0,
    },
    link: {
      type: 'string',
      description: '캐러셀 이미지 링크',
      example: 'https://www.kgu.ac.kr/',
    },
    fileId: {
      type: 'integer',
      format: 'int64',
      description: '캐러셀 이미지 ID',
      example: 1,
    },
  },
} as const

export const $AboutUpdateRequest = {
  type: 'object',
  description: '소개글 수정 request 객체 입니다.',
  properties: {
    content: {
      type: 'string',
      description: '페이지 내용(JSON 형식)',
      example: '{key:value}',
    },
  },
  required: ['content'],
} as const

export const $PageableResponseObject = {
  type: 'object',
  properties: {
    page: {
      type: 'integer',
      format: 'int32',
      default: '0',
      description:
        '페이지 인덱스로, 0부터 시작합니다. 별도의 값 없이 요청 시, 0으로 설정됩니다.',
    },
    size: {
      type: 'integer',
      format: 'int32',
      default: '10',
      description:
        '페이지 내 최대 응답 개수입니다. 별도의 값 없이 요청 시, 10으로 설정됩니다.',
    },
    totalPages: {
      type: 'integer',
      format: 'int32',
      default: '3',
      description: '전체 페이지 수 입니다.',
    },
    totalElements: {
      type: 'integer',
      format: 'int32',
      default: '30',
      description: '전체 요소 개수 입니다.',
    },
    isEnd: {
      type: 'boolean',
      default: 'false',
      description: '현재 응답하는 페이지가 마지막 일 시, true로 설정됩니다.',
    },
  },
  required: ['isEnd', 'page', 'size', 'totalElements', 'totalPages'],
} as const

export const $UserDetailPageResponse = {
  type: 'object',
  properties: {
    contents: {
      type: 'array',
      description: '유저 정보 리스트',
      example: [
        {
          name: '박민준',
          phone: '010-1234-5678',
          email: 'qkralswnsWkd@kyonggi.ac.kr',
          role: '학부생',
          major: '컴퓨터공학부',
          id: '202412345',
        },
      ],
      items: {
        $ref: '#/components/schemas/UserDetailResponse',
      },
    },
    pageable: {
      $ref: '#/components/schemas/PageableResponseObject',
      description: '페이징 정보',
    },
  },
  required: ['contents', 'pageable'],
} as const

export const $UserDetailResponse = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
      description: '이름',
      example: '박민준',
    },
    phone: {
      type: 'string',
      description: '전화번호',
      example: '010-1234-5678',
    },
    email: {
      type: 'string',
      description: '이메일',
      example: 'qkralswnsWkd@kyonggi.ac.kr',
    },
    role: {
      type: 'string',
      description: '구분',
      enum: ['USER', 'ADMIN', 'SUPER'],
      example: '학부생',
    },
    major: {
      type: 'string',
      description: '학과',
      enum: ['CSE', 'AIT', 'SSS'],
      example: '컴퓨터공학과',
    },
    id: {
      type: 'string',
      description: '학번(교번)',
      example: 202412345,
    },
  },
  required: ['email', 'id', 'major', 'name', 'phone', 'role'],
} as const
