// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { PostApiV1UsersDeleteData, PostApiV1UsersDeleteResponse, GetApiV1UsersData, GetApiV1UsersResponse, PostApiV1ProfessorsData, PostApiV1ProfessorsResponse, DeleteApiV1ProfessorsByIdData, DeleteApiV1ProfessorsByIdResponse, PatchApiV1ProfessorsByIdData, PatchApiV1ProfessorsByIdResponse, PostApiV1PostsData, PostApiV1PostsResponse, PatchApiV1PostsByPostIdData, PatchApiV1PostsByPostIdResponse, PatchApiV1PostsByPostIdPinData, PatchApiV1PostsByPostIdPinResponse, PatchApiV1PostsByPostIdDeleteData, PatchApiV1PostsByPostIdDeleteResponse, PostApiV1LabsData, PostApiV1LabsResponse, DeleteApiV1LabsByIdData, DeleteApiV1LabsByIdResponse, PatchApiV1LabsByIdData, PatchApiV1LabsByIdResponse, PostApiV1FilesPostData, PostApiV1FilesPostResponse, PostApiV1FilesLabData, PostApiV1FilesLabResponse, PostApiV1FilesClubData, PostApiV1FilesClubResponse, PostApiV1FilesCarouselData, PostApiV1FilesCarouselResponse, PostApiV1FilesAboutData, PostApiV1FilesAboutResponse, PostApiV1ClubsData, PostApiV1ClubsResponse, DeleteApiV1ClubsByIdData, DeleteApiV1ClubsByIdResponse, PatchApiV1ClubsByIdData, PatchApiV1ClubsByIdResponse, PostApiV1CarouselsData, PostApiV1CarouselsResponse, DeleteApiV1CarouselsByIdData, DeleteApiV1CarouselsByIdResponse, PatchApiV1CarouselsByIdData, PatchApiV1CarouselsByIdResponse, PostApiV1AboutsData, PostApiV1AboutsResponse, PatchApiV1AboutsByIdData, PatchApiV1AboutsByIdResponse } from './types.gen';

export class UserService {
    /**
     * 유저 삭제 API
     *     - Description : 이 API는 유저를 삭제합니다.
     * - Assignee : 이신행
     *
     * @param data The data for the request.
     * @param data.requestBody
     * @returns void No Content
     * @throws ApiError
     */
    public static postApiV1UsersDelete(data: PostApiV1UsersDeleteData): CancelablePromise<PostApiV1UsersDeleteResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/delete',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 유저 페이징 조회 API
     *     - Description : 이 API는 유저를 페이징 조회하며, 선택적으로 이름으로 필터링할 수 있습니다.
     * - Assignee : 박민준
     *
     * @param data The data for the request.
     * @param data.page 페이지 인덱스
     * @param data.size 응답 개수
     * @param data.name 유저 이름
     * @returns UserDetailPageResponse OK
     * @throws ApiError
     */
    public static getApiV1Users(data: GetApiV1UsersData): CancelablePromise<GetApiV1UsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users',
            query: {
                page: data.page,
                size: data.size,
                name: data.name
            }
        });
    }
    
}

export class ProfessorService {
    /**
     * 교수 생성 API
     *     - Description : 이 API는 교수를 생성합니다.
     * - Assignee : 이신행
     *
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ProfessorPersistResponse Created
     * @throws ApiError
     */
    public static postApiV1Professors(data: PostApiV1ProfessorsData): CancelablePromise<PostApiV1ProfessorsResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/professors',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 교수 삭제 API
     *     - Description : 이 API는 교수를 삭제합니다.
     * - Assignee : 이신행
     *
     * @param data The data for the request.
     * @param data.id 교수 ID는 URL 경로 변수 입니다.
     * @returns void No Content
     * @throws ApiError
     */
    public static deleteApiV1ProfessorsById(data: DeleteApiV1ProfessorsByIdData): CancelablePromise<DeleteApiV1ProfessorsByIdResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/professors/{id}',
            path: {
                id: data.id
            }
        });
    }
    
    /**
     * 교수 수정 API
     *     - Description : 이 API는 교수를 수정합니다.
     * - Assignee : 이신행
     *
     * @param data The data for the request.
     * @param data.id 교수 ID는 URL 경로 변수 입니다.
     * @param data.requestBody
     * @returns void No Content
     * @throws ApiError
     */
    public static patchApiV1ProfessorsById(data: PatchApiV1ProfessorsByIdData): CancelablePromise<PatchApiV1ProfessorsByIdResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/professors/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
}

export class PostService {
    /**
     * 게시글 생성 API
     * 	- Description : 이 API는 게시글을 생성합니다.
     * - Assignee : 박민준
     *
     * @param data The data for the request.
     * @param data.requestBody
     * @param data.fileId 게시글에 저장할 파일의 ID 입니다.
     * @returns PostPersistResponse Created
     * @throws ApiError
     */
    public static postApiV1Posts(data: PostApiV1PostsData): CancelablePromise<PostApiV1PostsResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/posts',
            query: {
                fileId: data.fileId
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 게시글 수정 API
     *     - Description : 이 API는 게시글을 수정합니다.
     * - Assignee : 박민준
     *
     * @param data The data for the request.
     * @param data.postId 게시글 ID는 URL 경로 변수 입니다.
     * @param data.requestBody
     * @returns void No Content
     * @throws ApiError
     */
    public static patchApiV1PostsByPostId(data: PatchApiV1PostsByPostIdData): CancelablePromise<PatchApiV1PostsByPostIdResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/posts/{postId}',
            path: {
                postId: data.postId
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 게시글 상단 고정 상태 토글 API
     *     - Description : 이 API는 지정된 게시글의 고정 여부를 토글하여 고정 또는 해제합니다.
     * - Assignee : 박민준
     *
     * @param data The data for the request.
     * @param data.postId 고정 상태를 변경할 게시글의 ID 입니다. URL 경로 변수 입니다.
     * @returns void No Content
     * @throws ApiError
     */
    public static patchApiV1PostsByPostIdPin(data: PatchApiV1PostsByPostIdPinData): CancelablePromise<PatchApiV1PostsByPostIdPinResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/posts/{postId}/pin',
            path: {
                postId: data.postId
            }
        });
    }
    
    /**
     * 게시글 삭제 API
     *     - Description : 이 API는 게시글을 삭제합니다.
     * - Assignee : 이신행
     *
     * @param data The data for the request.
     * @param data.postId 게시글 ID는 URL 경로 변수 입니다.
     * @returns void No Content
     * @throws ApiError
     */
    public static patchApiV1PostsByPostIdDelete(data: PatchApiV1PostsByPostIdDeleteData): CancelablePromise<PatchApiV1PostsByPostIdDeleteResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/posts/{postId}/delete',
            path: {
                postId: data.postId
            }
        });
    }
    
}

export class LabService {
    /**
     * 연구실 생성 API
     * 	- Description : 이 API는 연구실을 생성합니다.
     * - Assignee : 박민준
     *
     * @param data The data for the request.
     * @param data.requestBody
     * @param data.fileId 이미지 파일 ID는 URL 쿼리 파라미터 입니다.
     * @returns LabPersistResponse Created
     * @throws ApiError
     */
    public static postApiV1Labs(data: PostApiV1LabsData): CancelablePromise<PostApiV1LabsResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/labs',
            query: {
                fileId: data.fileId
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 연구실 삭제 API
     * 	- Description : 이 API는 해당 연구실을 삭제합니다.
     * - Assignee : 박민준
     *
     * @param data The data for the request.
     * @param data.id 연구실 ID는 URL 경로 변수 입니다.
     * @returns void No Content
     * @throws ApiError
     */
    public static deleteApiV1LabsById(data: DeleteApiV1LabsByIdData): CancelablePromise<DeleteApiV1LabsByIdResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/labs/{id}',
            path: {
                id: data.id
            }
        });
    }
    
    /**
     * 연구실 수정 API
     * 	- Description : 이 API는 연구실 정보를 수정합니다.
     * - Assignee : 박민준
     *
     * @param data The data for the request.
     * @param data.id 연구실 ID는 URL 경로 변수 입니다.
     * @param data.requestBody
     * @returns void No Content
     * @throws ApiError
     */
    public static patchApiV1LabsById(data: PatchApiV1LabsByIdData): CancelablePromise<PatchApiV1LabsByIdResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/labs/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
}

export class FileService {
    /**
     * 게시글 파일 업로드 API
     * 	- Description : 이 API는 게시글 첨부 파일을 업로드합니다. 한 게시글에 한 개의 파일만 업로드 가능합니다.
     * - Assignee : 이한음
     *
     * @param data The data for the request.
     * @param data.formData
     * @returns FilePathResponse Created
     * @throws ApiError
     */
    public static postApiV1FilesPost(data: PostApiV1FilesPostData = {}): CancelablePromise<PostApiV1FilesPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/files/post',
            formData: data.formData,
            mediaType: 'multipart/form-data'
        });
    }
    
    /**
     * 연구실 로고 이미지 업로드 API
     * 	- Description : 이 API는 연구실 로고 이미지를 업로드합니다. 한 로고 이미지에 한 개의 이미지만 업로드 가능합니다.
     * - Assignee : 박민준
     *
     * @param data The data for the request.
     * @param data.formData
     * @returns FilePathResponse Created
     * @throws ApiError
     */
    public static postApiV1FilesLab(data: PostApiV1FilesLabData = {}): CancelablePromise<PostApiV1FilesLabResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/files/lab',
            formData: data.formData,
            mediaType: 'multipart/form-data'
        });
    }
    
    /**
     * 동아리 로고 이미지 업로드 API
     * 	- Description : 이 API는 동아리 로고 이미지를 업로드합니다. 한 로고 이미지에 한 개의 이미지만 업로드 가능합니다.
     * - Assignee : 박민준
     *
     * @param data The data for the request.
     * @param data.formData
     * @returns FilePathResponse Created
     * @throws ApiError
     */
    public static postApiV1FilesClub(data: PostApiV1FilesClubData = {}): CancelablePromise<PostApiV1FilesClubResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/files/club',
            formData: data.formData,
            mediaType: 'multipart/form-data'
        });
    }
    
    /**
     * 캐러셀 이미지 업로드 API
     * 	- Description : 이 API는 캐러셀 이미지를 업로드합니다. 한 캐러셀에 한 개의 이미지만 업로드 가능합니다.
     * - Assignee : 이한음
     *
     * @param data The data for the request.
     * @param data.formData
     * @returns FilePathResponse Created
     * @throws ApiError
     */
    public static postApiV1FilesCarousel(data: PostApiV1FilesCarouselData = {}): CancelablePromise<PostApiV1FilesCarouselResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/files/carousel',
            formData: data.formData,
            mediaType: 'multipart/form-data'
        });
    }
    
    /**
     * 소개글 이미지 업로드 API
     * 	- Description : 이 API는 소개글 이미지를 업로드 합니다. 리스폰스의 physicalPath를 받아서 사용하면 됩니다.
     * - Assignee : 이한음
     *
     * @param data The data for the request.
     * @param data.formData
     * @returns FilePathResponse Created
     * @throws ApiError
     */
    public static postApiV1FilesAbout(data: PostApiV1FilesAboutData = {}): CancelablePromise<PostApiV1FilesAboutResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/files/about',
            formData: data.formData,
            mediaType: 'multipart/form-data'
        });
    }
    
}

export class ClubService {
    /**
     * 동아리 생성 API
     * 	- Description : 이 API는 동아리를 생성합니다.
     * - Assignee : 박민준
     *
     * @param data The data for the request.
     * @param data.requestBody
     * @param data.fileId 동아리 이미지에 저장할 파일의 ID 입니다.
     * @returns ClubPersistResponse Created
     * @throws ApiError
     */
    public static postApiV1Clubs(data: PostApiV1ClubsData): CancelablePromise<PostApiV1ClubsResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/clubs',
            query: {
                fileId: data.fileId
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 동아리 삭제 API
     * 	- Description : 이 API는 해당 동아리를 삭제합니다.
     * - Assignee : 박민준
     *
     * @param data The data for the request.
     * @param data.id 동아리 ID는 URL 경로 변수 입니다.
     * @returns void No Content
     * @throws ApiError
     */
    public static deleteApiV1ClubsById(data: DeleteApiV1ClubsByIdData): CancelablePromise<DeleteApiV1ClubsByIdResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/clubs/{id}',
            path: {
                id: data.id
            }
        });
    }
    
    /**
     * 동아리 수정 API
     * 	- Description : 이 API는 동아리 정보를 수정합니다.
     * - Assignee : 박민준
     *
     * @param data The data for the request.
     * @param data.id 동아리 ID는 URL 경로 변수 입니다.
     * @param data.requestBody
     * @returns void No Content
     * @throws ApiError
     */
    public static patchApiV1ClubsById(data: PatchApiV1ClubsByIdData): CancelablePromise<PatchApiV1ClubsByIdResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/clubs/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
}

export class CarouselService {
    /**
     * 캐러셀 저장 API
     * 	- Description : 이 API는 캐러셀 이미지와 기타 정보를 저장합니다.
     * - Assignee : 이한음
     *
     * @param data The data for the request.
     * @param data.fileId 캐러셀에 개시할 이미지의 ID 입니다.
     * @param data.requestBody
     * @returns CarouselPersistResponse Created
     * @throws ApiError
     */
    public static postApiV1Carousels(data: PostApiV1CarouselsData): CancelablePromise<PostApiV1CarouselsResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/carousels',
            query: {
                fileId: data.fileId
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 캐러셀 삭제 API
     * 	- Description : 이 API는 캐러셀을 삭제합니다.
     * - Assignee : 이한음
     *
     * @param data The data for the request.
     * @param data.id 캐러셀 ID는 URL 경로 변수 입니다.
     * @returns void No Content
     * @throws ApiError
     */
    public static deleteApiV1CarouselsById(data: DeleteApiV1CarouselsByIdData): CancelablePromise<DeleteApiV1CarouselsByIdResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/carousels/{id}',
            path: {
                id: data.id
            }
        });
    }
    
    /**
     * 캐러셀 수정 API
     * 	- Description : 이 API는 캐러셀을 수정합니다.
     * - Assignee : 박민준
     *
     * @param data The data for the request.
     * @param data.id 캐러셀 ID는 URL 경로 변수 입니다.
     * @param data.requestBody
     * @returns void No Content
     * @throws ApiError
     */
    public static patchApiV1CarouselsById(data: PatchApiV1CarouselsByIdData): CancelablePromise<PatchApiV1CarouselsByIdResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/carousels/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
}

export class AboutService {
    /**
     * 소개글 생성 API
     * 	- Description : 이 API는 소개글을 생성합니다.
     * - Assignee : 이신행
     *
     * @param data The data for the request.
     * @param data.requestBody
     * @returns AboutPersistResponse Created
     * @throws ApiError
     */
    public static postApiV1Abouts(data: PostApiV1AboutsData): CancelablePromise<PostApiV1AboutsResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/abouts',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 소개글 수정 API
     *     - Description : 이 API는 소개글을 수정합니다.
     * - Assignee : 이신행
     *
     * @param data The data for the request.
     * @param data.id 소개글 ID는 URL 경로 변수 입니다.
     * @param data.requestBody
     * @returns void No Content
     * @throws ApiError
     */
    public static patchApiV1AboutsById(data: PatchApiV1AboutsByIdData): CancelablePromise<PatchApiV1AboutsByIdResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/abouts/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
}