// This file is auto-generated by @hey-api/openapi-ts

export type UserKickOutListRequest = {
  /**
   * 학번 리스트
   */
  userIds: Array<string>
}

/**
 * 교수 수정 request 객체 입니다.
 */
export type ProfessorRequest = {
  /**
   * 교수 이름
   */
  name: string
  /**
   * 직위
   */
  role: string
  /**
   * 연락처
   */
  contact: string
  /**
   * 이메일
   */
  email: string
  /**
   * 이미지 URL
   */
  img: string
  /**
   * 연구실 위치
   */
  officeLoc: string
}

export type ProfessorPersistResponse = {
  /**
   * 교수 id
   */
  id: number
}

/**
 * 게시글 생성 request 객체 입니다.
 */
export type PostCreateRequest = {
  /**
   * 게시물 제목
   */
  title: string
  /**
   * 게시물 내용
   */
  content: string
  /**
   * 게시물 카테고리
   */
  category?: 'NOTIFICATION' | 'NEWS'
  /**
   * 게시글 고정 여부
   */
  isPinned: string
}

/**
 * 게시물 카테고리
 */
export type category = 'NOTIFICATION' | 'NEWS'

export type PostPersistResponse = {
  /**
   * 게시글 id
   */
  postId: number
}

/**
 * 연구실 생성 request 객체 입니다.
 */
export type LabCreateRequest = {
  /**
   * 연구실 이름
   */
  name: string
  /**
   * 연구실 위치
   */
  loc: string
  /**
   * 연구실 홈페이지
   */
  site: string
  /**
   * 연구실 담당교수
   */
  advisor: string
}

export type LabPersistResponse = {
  /**
   * 연구실 id
   */
  id: number
}

export type FilePathResponse = {
  /**
   * 파일 id
   */
  id: number
  /**
   * 파일 경로
   */
  physicalPath: string
}

/**
 * 동아리 생성 request 객체 입니다.
 */
export type ClubCreateRequest = {
  /**
   * 동아리 이름
   */
  name: string
  /**
   * 동아리 설명
   */
  description: string
  /**
   * 동아리 홈페이지
   */
  site?: string
}

export type ClubPersistResponse = {
  /**
   * 동아리 id
   */
  id: number
}

/**
 * 캐러셀 생성 request 객체 입니다.
 */
export type CarouselRequest = {
  /**
   * 캐러셀 설명
   */
  text?: string
  /**
   * 캐러셀 이미지 링크
   */
  link?: string
}

export type CarouselPersistResponse = {
  /**
   * 캐러셀 ID
   */
  id: number
}

/**
 * 소개글 생성 request 객체 입니다.
 */
export type AboutCreateRequest = {
  /**
   * 카테고리
   */
  category: 'DEPT_INTRO' | 'DIRECTIONS'
  /**
   * 페이지 내용(JSON 형식)
   */
  content: string
}

/**
 * 카테고리
 */
export type category2 = 'DEPT_INTRO' | 'DIRECTIONS'

export type AboutPersistResponse = {
  /**
   * 소개글 id
   */
  id: number
}

/**
 * 게시글 수정 request 객체 입니다.
 */
export type PostUpdateRequest = {
  /**
   * 게시물 제목
   */
  title: string
  /**
   * 게시물 내용
   */
  content: string
  /**
   * 게시물 카테고리
   */
  category?: 'NOTIFICATION' | 'NEWS'
  /**
   * 파일 ID
   */
  fileId?: number
  /**
   * 게시글 고정 여부
   */
  isPinned: string
}

/**
 * 연구실 수정 request 객체 입니다.
 */
export type LabUpdateRequest = {
  /**
   * 연구실 이름
   */
  name: string
  /**
   * 연구실 위치
   */
  loc: string
  /**
   * 연구실 홈페이지
   */
  site: string
  /**
   * 연구실 담당교수
   */
  advisor: string
  /**
   * 파일 ID
   */
  fileId?: number
}

/**
 * 동아리 수정 request 객체 입니다.
 */
export type ClubUpdateRequest = {
  /**
   * 동아리 이름
   */
  name: string
  /**
   * 동아리 설명
   */
  description: string
  /**
   * 동아리 홈페이지
   */
  site?: string
  /**
   * 파일 ID
   */
  fileId?: number
}

/**
 * 캐러셀 생성 request 객체 입니다.
 */
export type CarouselUpdateRequest = {
  /**
   * 캐러셀 설명
   */
  text?: string
  /**
   * 캐러셀 이미지 링크
   */
  link?: string
  /**
   * 캐러셀 이미지 ID
   */
  fileId?: number
}

/**
 * 소개글 수정 request 객체 입니다.
 */
export type AboutUpdateRequest = {
  /**
   * 페이지 내용(JSON 형식)
   */
  content: string
}

export type PageableResponseObject = {
  /**
   * 페이지 인덱스로, 0부터 시작합니다. 별도의 값 없이 요청 시, 0으로 설정됩니다.
   */
  page: number
  /**
   * 페이지 내 최대 응답 개수입니다. 별도의 값 없이 요청 시, 10으로 설정됩니다.
   */
  size: number
  /**
   * 전체 페이지 수 입니다.
   */
  totalPages: number
  /**
   * 전체 요소 개수 입니다.
   */
  totalElements: number
  /**
   * 현재 응답하는 페이지가 마지막 일 시, true로 설정됩니다.
   */
  isEnd: boolean
}

export type UserDetailPageResponse = {
  /**
   * 유저 정보 리스트
   */
  contents: Array<UserDetailResponse>
  /**
   * 페이징 정보
   */
  pageable: PageableResponseObject
}

export type UserDetailResponse = {
  /**
   * 이름
   */
  name: string
  /**
   * 전화번호
   */
  phone: string
  /**
   * 이메일
   */
  email: string
  /**
   * 구분
   */
  role: 'USER' | 'ADMIN' | 'SUPER'
  /**
   * 학과
   */
  major: 'CSE' | 'AIT' | 'SSS'
  /**
   * 학번(교번)
   */
  id: string
}

/**
 * 구분
 */
export type role = 'USER' | 'ADMIN' | 'SUPER'

/**
 * 학과
 */
export type major = 'CSE' | 'AIT' | 'SSS'

export type PostApiV1UsersDeleteData = {
  requestBody: UserKickOutListRequest
}

export type PostApiV1UsersDeleteResponse = void

export type GetApiV1UsersData = {
  /**
   * 유저 이름
   */
  name?: string
  /**
   * 페이지 인덱스
   */
  page: number
  /**
   * 응답 개수
   */
  size: number
}

export type GetApiV1UsersResponse = UserDetailPageResponse

export type PostApiV1ProfessorsData = {
  requestBody: ProfessorRequest
}

export type PostApiV1ProfessorsResponse = ProfessorPersistResponse

export type DeleteApiV1ProfessorsByIdData = {
  /**
   * 교수 ID는 URL 경로 변수 입니다.
   */
  id: number
}

export type DeleteApiV1ProfessorsByIdResponse = void

export type PatchApiV1ProfessorsByIdData = {
  /**
   * 교수 ID는 URL 경로 변수 입니다.
   */
  id: number
  requestBody: ProfessorRequest
}

export type PatchApiV1ProfessorsByIdResponse = void

export type PostApiV1PostsData = {
  /**
   * 게시글에 저장할 파일의 ID 입니다.
   */
  fileId?: number
  requestBody: PostCreateRequest
}

export type PostApiV1PostsResponse = PostPersistResponse

export type PatchApiV1PostsByPostIdData = {
  /**
   * 게시글 ID는 URL 경로 변수 입니다.
   */
  postId: number
  requestBody: PostUpdateRequest
}

export type PatchApiV1PostsByPostIdResponse = void

export type PatchApiV1PostsByPostIdPinData = {
  /**
   * 고정 상태를 변경할 게시글의 ID 입니다. URL 경로 변수 입니다.
   */
  postId: number
}

export type PatchApiV1PostsByPostIdPinResponse = void

export type PatchApiV1PostsByPostIdDeleteData = {
  /**
   * 게시글 ID는 URL 경로 변수 입니다.
   */
  postId: number
}

export type PatchApiV1PostsByPostIdDeleteResponse = void

export type PostApiV1LabsData = {
  /**
   * 이미지 파일 ID는 URL 쿼리 파라미터 입니다.
   */
  fileId?: number
  requestBody: LabCreateRequest
}

export type PostApiV1LabsResponse = LabPersistResponse

export type DeleteApiV1LabsByIdData = {
  /**
   * 연구실 ID는 URL 경로 변수 입니다.
   */
  id: number
}

export type DeleteApiV1LabsByIdResponse = void

export type PatchApiV1LabsByIdData = {
  /**
   * 연구실 ID는 URL 경로 변수 입니다.
   */
  id: number
  requestBody: LabUpdateRequest
}

export type PatchApiV1LabsByIdResponse = void

export type PostApiV1FilesPostData = {
  formData?: {
    /**
     * 게시글 첨부 파일
     */
    file: Blob | File
  }
}

export type PostApiV1FilesPostResponse = FilePathResponse

export type PostApiV1FilesLabData = {
  formData?: {
    /**
     * 연구실 로고 이미지
     */
    file: Blob | File
  }
}

export type PostApiV1FilesLabResponse = FilePathResponse

export type PostApiV1FilesClubData = {
  formData?: {
    /**
     * 동아리 로고 이미지
     */
    file: Blob | File
  }
}

export type PostApiV1FilesClubResponse = FilePathResponse

export type PostApiV1FilesCarouselData = {
  formData?: {
    /**
     * 캐러셀 이미지
     */
    file: Blob | File
  }
}

export type PostApiV1FilesCarouselResponse = FilePathResponse

export type PostApiV1FilesAboutData = {
  formData?: {
    /**
     * 소개글 첨부 이미지
     */
    file: Blob | File
  }
}

export type PostApiV1FilesAboutResponse = FilePathResponse

export type PostApiV1ClubsData = {
  /**
   * 동아리 이미지에 저장할 파일의 ID 입니다.
   */
  fileId?: number
  requestBody: ClubCreateRequest
}

export type PostApiV1ClubsResponse = ClubPersistResponse

export type DeleteApiV1ClubsByIdData = {
  /**
   * 동아리 ID는 URL 경로 변수 입니다.
   */
  id: number
}

export type DeleteApiV1ClubsByIdResponse = void

export type PatchApiV1ClubsByIdData = {
  /**
   * 동아리 ID는 URL 경로 변수 입니다.
   */
  id: number
  requestBody: ClubUpdateRequest
}

export type PatchApiV1ClubsByIdResponse = void

export type PostApiV1CarouselsData = {
  /**
   * 캐러셀에 개시할 이미지의 ID 입니다.
   */
  fileId: number
  requestBody: CarouselRequest
}

export type PostApiV1CarouselsResponse = CarouselPersistResponse

export type DeleteApiV1CarouselsByIdData = {
  /**
   * 캐러셀 ID는 URL 경로 변수 입니다.
   */
  id: number
}

export type DeleteApiV1CarouselsByIdResponse = void

export type PatchApiV1CarouselsByIdData = {
  /**
   * 캐러셀 ID는 URL 경로 변수 입니다.
   */
  id: number
  requestBody: CarouselUpdateRequest
}

export type PatchApiV1CarouselsByIdResponse = void

export type PostApiV1AboutsData = {
  requestBody: AboutCreateRequest
}

export type PostApiV1AboutsResponse = AboutPersistResponse

export type PatchApiV1AboutsByIdData = {
  /**
   * 소개글 ID는 URL 경로 변수 입니다.
   */
  category: 'DEPT_INTRO' | 'DIRECTIONS'
  requestBody: AboutUpdateRequest
}

export type PatchApiV1AboutsByIdResponse = void

export type $OpenApiTs = {
  '/api/v1/users/delete': {
    post: {
      req: PostApiV1UsersDeleteData
      res: {
        /**
         * No Content
         */
        204: void
      }
    }
  }
  '/api/v1/users': {
    get: {
      req: GetApiV1UsersData
      res: {
        /**
         * OK
         */
        200: UserDetailPageResponse
      }
    }
  }
  '/api/v1/professors': {
    post: {
      req: PostApiV1ProfessorsData
      res: {
        /**
         * Created
         */
        201: ProfessorPersistResponse
      }
    }
  }
  '/api/v1/professors/{id}': {
    delete: {
      req: DeleteApiV1ProfessorsByIdData
      res: {
        /**
         * No Content
         */
        204: void
      }
    }
    patch: {
      req: PatchApiV1ProfessorsByIdData
      res: {
        /**
         * No Content
         */
        204: void
      }
    }
  }
  '/api/v1/posts': {
    post: {
      req: PostApiV1PostsData
      res: {
        /**
         * Created
         */
        201: PostPersistResponse
      }
    }
  }
  '/api/v1/posts/{postId}': {
    patch: {
      req: PatchApiV1PostsByPostIdData
      res: {
        /**
         * No Content
         */
        204: void
      }
    }
  }
  '/api/v1/posts/{postId}/pin': {
    patch: {
      req: PatchApiV1PostsByPostIdPinData
      res: {
        /**
         * No Content
         */
        204: void
      }
    }
  }
  '/api/v1/posts/{postId}/delete': {
    patch: {
      req: PatchApiV1PostsByPostIdDeleteData
      res: {
        /**
         * No Content
         */
        204: void
      }
    }
  }
  '/api/v1/labs': {
    post: {
      req: PostApiV1LabsData
      res: {
        /**
         * Created
         */
        201: LabPersistResponse
      }
    }
  }
  '/api/v1/labs/{id}': {
    delete: {
      req: DeleteApiV1LabsByIdData
      res: {
        /**
         * No Content
         */
        204: void
      }
    }
    patch: {
      req: PatchApiV1LabsByIdData
      res: {
        /**
         * No Content
         */
        204: void
      }
    }
  }
  '/api/v1/files/post': {
    post: {
      req: PostApiV1FilesPostData
      res: {
        /**
         * Created
         */
        201: FilePathResponse
      }
    }
  }
  '/api/v1/files/lab': {
    post: {
      req: PostApiV1FilesLabData
      res: {
        /**
         * Created
         */
        201: FilePathResponse
      }
    }
  }
  '/api/v1/files/club': {
    post: {
      req: PostApiV1FilesClubData
      res: {
        /**
         * Created
         */
        201: FilePathResponse
      }
    }
  }
  '/api/v1/files/carousel': {
    post: {
      req: PostApiV1FilesCarouselData
      res: {
        /**
         * Created
         */
        201: FilePathResponse
      }
    }
  }
  '/api/v1/files/about': {
    post: {
      req: PostApiV1FilesAboutData
      res: {
        /**
         * Created
         */
        201: FilePathResponse
      }
    }
  }
  '/api/v1/clubs': {
    post: {
      req: PostApiV1ClubsData
      res: {
        /**
         * Created
         */
        201: ClubPersistResponse
      }
    }
  }
  '/api/v1/clubs/{id}': {
    delete: {
      req: DeleteApiV1ClubsByIdData
      res: {
        /**
         * No Content
         */
        204: void
      }
    }
    patch: {
      req: PatchApiV1ClubsByIdData
      res: {
        /**
         * No Content
         */
        204: void
      }
    }
  }
  '/api/v1/carousels': {
    post: {
      req: PostApiV1CarouselsData
      res: {
        /**
         * Created
         */
        201: CarouselPersistResponse
      }
    }
  }
  '/api/v1/carousels/{id}': {
    delete: {
      req: DeleteApiV1CarouselsByIdData
      res: {
        /**
         * No Content
         */
        204: void
      }
    }
    patch: {
      req: PatchApiV1CarouselsByIdData
      res: {
        /**
         * No Content
         */
        204: void
      }
    }
  }
  '/api/v1/abouts': {
    post: {
      req: PostApiV1AboutsData
      res: {
        /**
         * Created
         */
        201: AboutPersistResponse
      }
    }
  }
  '/api/v1/abouts/{id}': {
    patch: {
      req: PatchApiV1AboutsByIdData
      res: {
        /**
         * No Content
         */
        204: void
      }
    }
  }
}
