services:
  aics-client:
    build:
      context: .
      dockerfile: dockerfile
    image: aics-client:latest
    container_name: aics-client
    ports:
      - '3000:3000'
    restart: unless-stopped
    networks:
      - aics-network

  aics-graduate:
    build:
      context: .
      dockerfile: apps/graduate/Dockerfile
    image: aics-graduate:latest
    container_name: aics-graduate
    ports:
      - '3001:3001'
    restart: unless-stopped
    networks:
      - aics-network

networks:
  aics-network:
    driver: bridge
