// This file is auto-generated by @hey-api/openapi-ts

export const $UserCreateRequest = {
  type: 'object',
  description: '회원 가입 request 객체 입니다.',
  properties: {
    userId: {
      type: 'string',
      description: '학번',
      example: 202412345,
      pattern: '\\d{9}',
    },
    password: {
      type: 'string',
      description: '비밀번호',
      example: 'password1234!',
      pattern:
        '^(?=.*[A-Za-z])(?=.*\\d)(?=.*[!@#$%^&*(),.?":{}|<>])[A-Za-z\\d!@#$%^&*(),.?":{}|<>]{8,15}$',
    },
    name: {
      type: 'string',
      description: '이름',
      example: '박민준',
    },
    email: {
      type: 'string',
      description: '이메일',
      example: 'qkralswnsWkd@kyonggi.ac.kr',
      pattern: '^[A-Za-z0-9._%+-]+@(kyonggi|kgu)\\.ac\\.kr$',
    },
    phone: {
      type: 'string',
      description: '전화번호',
      example: '010-1234-5678',
      pattern: '^\\d{2,4}-\\d{3,4}-\\d{4}$',
    },
    major: {
      type: 'string',
      description: '전공 이름',
      enum: ['CSE', 'AIT', 'SSS'],
      example: 'CSE',
    },
  },
  required: ['email', 'major', 'name', 'password', 'phone', 'userId'],
} as const

export const $UserPersistResponse = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      description: '유저 id',
      example: 202412345,
    },
  },
  required: ['id'],
} as const

export const $CommentRequest = {
  type: 'object',
  description: '댓글 생성 request 객체 입니다.',
  properties: {
    postId: {
      type: 'integer',
      format: 'int64',
      description: '게시물 아이디',
      example: 1,
    },
    content: {
      type: 'string',
      description: '댓글 내용',
      example: '예시 코멘트입니다, 좋은 소식이네요!',
    },
  },
  required: ['content', 'postId'],
} as const

export const $CommentPersistResponse = {
  type: 'object',
  properties: {
    commentId: {
      type: 'integer',
      format: 'int64',
      description: '댓글 id',
      example: 1,
    },
  },
  required: ['commentId'],
} as const

export const $UserUpdateRequest = {
  type: 'object',
  properties: {
    phone: {
      type: 'string',
      description: '전화번호',
      example: '010-1234-5678',
      pattern: '^\\d{2,4}-\\d{3,4}-\\d{4}$',
    },
    email: {
      type: 'string',
      description: '이메일',
      example: 'qkralswnsWkd@kyonggi.ac.kr',
      pattern: '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6}$',
    },
  },
  required: ['email', 'phone'],
} as const

export const $UserPasswordUpdateRequest = {
  type: 'object',
  description: '회원 비밀번호 수정 request 객체 입니다.',
  properties: {
    originalPassword: {
      type: 'string',
      description: '원래 비밀번호',
      example: 'password1234!',
      pattern:
        '^(?=.*[A-Za-z])(?=.*\\d)(?=.*[!@#$%^&*(),.?":{}|<>])[A-Za-z\\d!@#$%^&*(),.?":{}|<>]{8,15}$',
    },
    newPassword: {
      type: 'string',
      description: '새로운 비밀번호',
      example: 'newpass1234!',
      pattern:
        '^(?=.*[A-Za-z])(?=.*\\d)(?=.*[!@#$%^&*(),.?":{}|<>])[A-Za-z\\d!@#$%^&*(),.?":{}|<>]{8,15}$',
    },
  },
  required: ['newPassword', 'originalPassword'],
} as const

export const $CommentUpdateRequest = {
  type: 'object',
  description: '댓글 수정 request 객체 입니다.',
  properties: {
    content: {
      type: 'string',
      description: '댓글 내용',
      example: '예시 코멘트입니다, 좋은 소식이네요!',
    },
  },
  required: ['content'],
} as const

export const $UserDetailResponse = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
      description: '이름',
      example: '박민준',
    },
    phone: {
      type: 'string',
      description: '전화번호',
      example: '010-1234-5678',
    },
    email: {
      type: 'string',
      description: '이메일',
      example: 'qkralswnsWkd@kyonggi.ac.kr',
    },
    role: {
      type: 'string',
      description: '구분',
      enum: ['USER', 'ADMIN', 'SUPER'],
      example: '학부생',
    },
    major: {
      type: 'string',
      description: '학과',
      enum: ['CSE', 'AIT', 'SSS'],
      example: '컴퓨터공학과',
    },
    id: {
      type: 'string',
      description: '학번(교번)',
      example: 202412345,
    },
  },
  required: ['email', 'id', 'major', 'name', 'phone', 'role'],
} as const

export const $ProfessorListResponse = {
  type: 'object',
  properties: {
    contents: {
      type: 'array',
      description: '교수 리스트',
      example: [
        {
          id: 1,
          name: '이은정',
          role: '조교수',
          contact: '031-249-9671',
          officeLoc: '8213호',
          email: 'ejlee@kyonggi.ac.kr',
          img: 'https://image.com/professor/profile/image',
        },
      ],
      items: {
        $ref: '#/components/schemas/ProfessorResponse',
      },
    },
  },
  required: ['contents'],
} as const

export const $ProfessorResponse = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      format: 'int64',
      description: '교수 id',
      example: 1,
    },
    name: {
      type: 'string',
      description: '교수 이름',
      example: '이은정',
    },
    role: {
      type: 'string',
      description: '직위',
      example: '조교수',
    },
    contact: {
      type: 'string',
      description: '연락처',
      example: '031-249-9671',
    },
    officeLoc: {
      type: 'string',
      description: '연구실 위치',
      example: '8213호',
    },
    email: {
      type: 'string',
      description: '이메일',
      example: 'ejlee@kyonggi.ac.kr',
    },
    img: {
      type: 'string',
      description: '이미지 URL',
      example: 'https://image.com/professor/profile/image',
    },
  },
  required: ['contact', 'email', 'id', 'img', 'name', 'officeLoc', 'role'],
} as const

export const $PageableResponseObject = {
  type: 'object',
  properties: {
    page: {
      type: 'integer',
      format: 'int32',
      default: '0',
      description:
        '페이지 인덱스로, 0부터 시작합니다. 별도의 값 없이 요청 시, 0으로 설정됩니다.',
    },
    size: {
      type: 'integer',
      format: 'int32',
      default: '10',
      description:
        '페이지 내 최대 응답 개수입니다. 별도의 값 없이 요청 시, 10으로 설정됩니다.',
    },
    totalPages: {
      type: 'integer',
      format: 'int32',
      default: '3',
      description: '전체 페이지 수 입니다.',
    },
    totalElements: {
      type: 'integer',
      format: 'int32',
      default: '30',
      description: '전체 요소 개수 입니다.',
    },
    isEnd: {
      type: 'boolean',
      default: 'false',
      description: '현재 응답하는 페이지가 마지막 일 시, true로 설정됩니다.',
    },
  },
  required: ['isEnd', 'page', 'size', 'totalElements', 'totalPages'],
} as const

export const $PostSummaryPageResponse = {
  type: 'object',
  properties: {
    contents: {
      type: 'array',
      description: '게시글 정보 리스트',
      example: [
        {
          postId: 3,
          category: '공지사항',
          title: 'SW 부트캠프 4기 교육생 모집',
          author: '홈피관리자',
          description: '2024학년도 학과 소개가 아래와 같은 일정으로 진행됩',
          views: 19,
          hasAttachment: false,
          isPinned: false,
          createdAt: '2024-11-11',
        },
      ],
      items: {
        $ref: '#/components/schemas/PostSummaryResponse',
      },
    },
    pageable: {
      $ref: '#/components/schemas/PageableResponseObject',
      description: '페이징 정보',
    },
  },
  required: ['contents', 'pageable'],
} as const

export const $PostSummaryResponse = {
  type: 'object',
  properties: {
    postId: {
      type: 'integer',
      format: 'int64',
      description: '게시글 id',
      example: 1,
    },
    category: {
      type: 'string',
      description: '게시글 카테고리',
      example: '학과공지',
    },
    title: {
      type: 'string',
      description: '게시글 제목',
      example: 'SW 부트캠프 4기 교육생 모집',
    },
    author: {
      type: 'string',
      description: '작성자 이름',
      example: '홈피관리자',
    },
    description: {
      type: 'string',
      description: '게시글 내용 앞부분 30자',
      example: '2024학년도 학과 소개가 아래와 같은 일정으로 진행됩',
    },
    views: {
      type: 'integer',
      format: 'int32',
      description: '조회수',
      example: 19,
    },
    hasAttachment: {
      type: 'boolean',
      description: '첨부파일 여부',
      example: false,
    },
    isPinned: {
      type: 'boolean',
      description: '상단 고정 여부',
      example: false,
    },
    createdAt: {
      type: 'string',
      description: '작성일',
      example: '2024-11-11',
    },
  },
  required: [
    'author',
    'category',
    'createdAt',
    'description',
    'hasAttachment',
    'isPinned',
    'postId',
    'title',
    'views',
  ],
} as const

export const $FilePathResponse = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      format: 'int64',
      description: '파일 id',
      example: 1,
    },
    physicalPath: {
      type: 'string',
      description: '파일 경로',
      example: '/files/2025-curriculum',
    },
  },
  required: ['id', 'physicalPath'],
} as const

export const $PostDetailResponse = {
  type: 'object',
  properties: {
    postId: {
      type: 'integer',
      format: 'int64',
      description: '게시글 id',
      example: 2,
    },
    category: {
      type: 'string',
      description: '게시글 카테고리',
      example: '학과공지',
    },
    title: {
      type: 'string',
      description: '게시글 제목',
      example: 'SW 부트캠프 4기 교육생 모집',
    },
    content: {
      type: 'string',
      description: '내용',
      example: `SW 부트캠프 4기 교육생 모집
SW전문인재양성사업단에서는 SW부트캠프 4기 교육생을 모집합니다.
관심있는 학생들의 많은 신청 바랍니다.
- 모집기간 : 2024.10.07(월)~10.15(화)
- 신청방법 :https://kebkyonggi.quv.kr/68
`,
    },
    author: {
      type: 'string',
      description: '작성자 이름',
      example: '홈피관리자',
    },
    views: {
      type: 'integer',
      format: 'int32',
      description: '조회수',
      example: 19,
    },
    isPinned: {
      type: 'boolean',
      description: '상단 고정 여부',
      example: false,
    },
    file: {
      $ref: '#/components/schemas/FilePathResponse',
      description: '첨부 파일 정보',
      example: {
        physicalPath: '/cloud/file/3/2025-curriculum',
      },
    },
    createdAt: {
      type: 'string',
      description: '작성일',
      example: '2024-11-11 15:45',
    },
    prevPost: {
      $ref: '#/components/schemas/PostTitleResponse',
      description: '이전 게시글 정보',
      example: {
        id: 1,
        title: '이전 게시글 제목',
      },
    },
    nextPost: {
      $ref: '#/components/schemas/PostTitleResponse',
      description: '다음 게시글 정보',
      example: {
        id: 3,
        title: '다음 게시글 제목',
      },
    },
  },
  required: [
    'author',
    'category',
    'content',
    'createdAt',
    'isPinned',
    'postId',
    'title',
    'views',
  ],
} as const

export const $PostTitleResponse = {
  type: 'object',
  properties: {
    postId: {
      type: 'integer',
      format: 'int64',
      description: '게시글 id',
      example: 1,
    },
    title: {
      type: 'string',
      description: '게시글 제목',
      example: 'SW 부트캠프 4기 교육생 모집',
    },
  },
  required: ['postId', 'title'],
} as const

export const $LabDetailResponse = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      format: 'int64',
      description: '연구실 id',
      example: 1,
    },
    name: {
      type: 'string',
      description: '연구실 이름',
      example: '보안 연구실',
    },
    loc: {
      type: 'string',
      description: '연구실 위치',
      example: '8502, 8503',
    },
    site: {
      type: 'string',
      description: '연구실 사이트',
      example: 'http://ailab.kyonggi.ac.kr',
    },
    advisor: {
      type: 'string',
      description: '연구실 담당교수',
      example: '박민준',
    },
    img: {
      $ref: '#/components/schemas/FilePathResponse',
      description: '연구실 이미지 파일',
      example: {
        id: 1,
        physicalPath: '/files/lab/20250131/lab-A.png',
      },
    },
  },
  required: ['advisor', 'id', 'loc', 'name', 'site'],
} as const

export const $LabListResponse = {
  type: 'object',
  properties: {
    contents: {
      type: 'array',
      description: '등록된 연구실 리스트',
      example: [
        {
          id: 1,
          name: '인공지능연구실',
          loc: '8502, 8503',
          site: 'http://ailab.kyonggi.ac.kr',
          professor: '박민준',
          img: {
            id: 1,
            physicalPath: '/files/lab/20250131/lab-A.png',
          },
        },
      ],
      items: {
        $ref: '#/components/schemas/LabDetailResponse',
      },
    },
  },
  required: ['contents'],
} as const

export const $CommentListResponse = {
  type: 'object',
  properties: {
    contents: {
      type: 'array',
      description: '게시글에 첨부된 파일',
      example: [
        {
          commentId: 1,
          author: '이신행',
          createdAt: '2024-11-11',
          content: '예시 코멘트입니다, 좋은 소식이네요!',
        },
      ],
      items: {
        $ref: '#/components/schemas/CommentResponse',
      },
    },
  },
  required: ['contents'],
} as const

export const $CommentResponse = {
  type: 'object',
  properties: {
    commentId: {
      type: 'integer',
      format: 'int64',
      description: '댓글 id',
      example: 1,
    },
    author: {
      type: 'string',
      description: '작성자 이름',
      example: '이신행',
    },
    createdAt: {
      type: 'string',
      description: '작성일',
      example: '2024-11-11',
    },
    content: {
      type: 'string',
      description: '내용',
      example: '예시 코멘트입니다, 좋은 소식이네요!',
    },
  },
  required: ['author', 'commentId', 'content', 'createdAt'],
} as const

export const $ClubDetailResponse = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      format: 'int64',
      description: '동아리 id',
      example: 1,
    },
    name: {
      type: 'string',
      description: '동아리 이름',
      example: 'C-Lab',
    },
    description: {
      type: 'string',
      description: '동아리 설명',
      example: '경기대학교 AI컴퓨터공학부 개발동아리입니다.',
    },
    site: {
      type: 'string',
      description: '동아리 사이트',
      example: 'https://www.clab.page/',
    },
    file: {
      $ref: '#/components/schemas/FilePathResponse',
      description: '첨부 파일 정보',
      example: {
        physicalPath: '/cloud/file/3/2025-curriculum',
      },
    },
  },
  required: ['description', 'id', 'name'],
} as const

export const $ClubListResponse = {
  type: 'object',
  properties: {
    contents: {
      type: 'array',
      description: '등록된 동아리 리스트',
      example: [
        {
          id: 1,
          name: 'C-Lab',
          description: '경기대학교 AI컴퓨터공학부 개발동아리입니다.',
          site: 'https://www.clab.page/',
        },
      ],
      items: {
        $ref: '#/components/schemas/ClubDetailResponse',
      },
    },
  },
  required: ['contents'],
} as const

export const $CarouselListResponse = {
  type: 'object',
  properties: {
    contents: {
      type: 'array',
      description: '캐러셀 리스트',
      example: [
        {
          id: 1,
          text: '경기대학교 AI컴퓨터공학부 메인 이미지',
          link: 'https://www.kgu.ac.kr/',
          file: {
            id: 1,
            physicalPath: '/cloud/carousel/3/2025-curriculum',
          },
        },
      ],
      items: {
        $ref: '#/components/schemas/CarouselResponse',
      },
    },
  },
  required: ['contents'],
} as const

export const $CarouselResponse = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      format: 'int64',
      description: '캐러셀 ID',
      example: 1,
    },
    text: {
      type: 'string',
      description: '캐러셀 설명',
      example: '경기대학교 AI컴퓨터공학부 메인 이미지',
    },
    link: {
      type: 'string',
      description: '캐러셀 이미지 링크',
      example: 'https://www.kgu.ac.kr/',
    },
    file: {
      $ref: '#/components/schemas/FilePathResponse',
      description: '첨부 파일 정보',
      example: {
        id: 1,
        physicalPath: '/files/2025-curriculum',
      },
    },
  },
  required: ['id'],
} as const

export const $AboutResponse = {
  type: 'object',
  properties: {
    content: {
      type: 'string',
      description: '페이지 내용(JSON 형식)',
      example: '{key:value}',
    },
  },
  required: ['content'],
} as const
