server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /proxy-api/ {
        proxy_pass http://aics-api:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /proxy-admin/ {
        proxy_pass http://aics-admin:8081/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /proxy-auth/ {
        proxy_pass http://aics-auth:8082/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    access_log /var/log/nginx/graduate_access.log;
    error_log /var/log/nginx/graduate_error.log;
}