/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AfterLoginRouteImport } from './routes/_afterLogin'
import { Route as AfterLoginIndexRouteImport } from './routes/_afterLogin/index'
import { Route as AfterLoginThesisRouteImport } from './routes/_afterLogin/thesis'
import { Route as AfterLoginStatusRouteImport } from './routes/_afterLogin/status'
import { Route as AfterLoginScheduleRouteImport } from './routes/_afterLogin/schedule'
import { Route as AfterLoginGuidelinesAndRulesRouteImport } from './routes/_afterLogin/guidelines-and-rules'
import { Route as AfterLoginGraduatesAllRouteImport } from './routes/_afterLogin/graduates-all'
import { Route as AfterLoginCertificationRouteImport } from './routes/_afterLogin/certification'
import { Route as AfterLoginApplyRouteImport } from './routes/_afterLogin/apply'
import { Route as AfterLoginNoticesIndexRouteImport } from './routes/_afterLogin/notices/index'
import { Route as AfterLoginNoticesCreateRouteImport } from './routes/_afterLogin/notices/create'
import { Route as AfterLoginNoticesPostIdRouteImport } from './routes/_afterLogin/notices/$postId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AfterLoginRoute = AfterLoginRouteImport.update({
  id: '/_afterLogin',
  getParentRoute: () => rootRouteImport,
} as any)
const AfterLoginIndexRoute = AfterLoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AfterLoginRoute,
} as any)
const AfterLoginThesisRoute = AfterLoginThesisRouteImport.update({
  id: '/thesis',
  path: '/thesis',
  getParentRoute: () => AfterLoginRoute,
} as any)
const AfterLoginStatusRoute = AfterLoginStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AfterLoginRoute,
} as any)
const AfterLoginScheduleRoute = AfterLoginScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AfterLoginRoute,
} as any)
const AfterLoginGuidelinesAndRulesRoute =
  AfterLoginGuidelinesAndRulesRouteImport.update({
    id: '/guidelines-and-rules',
    path: '/guidelines-and-rules',
    getParentRoute: () => AfterLoginRoute,
  } as any)
const AfterLoginGraduatesAllRoute = AfterLoginGraduatesAllRouteImport.update({
  id: '/graduates-all',
  path: '/graduates-all',
  getParentRoute: () => AfterLoginRoute,
} as any)
const AfterLoginCertificationRoute = AfterLoginCertificationRouteImport.update({
  id: '/certification',
  path: '/certification',
  getParentRoute: () => AfterLoginRoute,
} as any)
const AfterLoginApplyRoute = AfterLoginApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => AfterLoginRoute,
} as any)
const AfterLoginNoticesIndexRoute = AfterLoginNoticesIndexRouteImport.update({
  id: '/notices/',
  path: '/notices/',
  getParentRoute: () => AfterLoginRoute,
} as any)
const AfterLoginNoticesCreateRoute = AfterLoginNoticesCreateRouteImport.update({
  id: '/notices/create',
  path: '/notices/create',
  getParentRoute: () => AfterLoginRoute,
} as any)
const AfterLoginNoticesPostIdRoute = AfterLoginNoticesPostIdRouteImport.update({
  id: '/notices/$postId',
  path: '/notices/$postId',
  getParentRoute: () => AfterLoginRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/apply': typeof AfterLoginApplyRoute
  '/certification': typeof AfterLoginCertificationRoute
  '/graduates-all': typeof AfterLoginGraduatesAllRoute
  '/guidelines-and-rules': typeof AfterLoginGuidelinesAndRulesRoute
  '/schedule': typeof AfterLoginScheduleRoute
  '/status': typeof AfterLoginStatusRoute
  '/thesis': typeof AfterLoginThesisRoute
  '/': typeof AfterLoginIndexRoute
  '/notices/$postId': typeof AfterLoginNoticesPostIdRoute
  '/notices/create': typeof AfterLoginNoticesCreateRoute
  '/notices': typeof AfterLoginNoticesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/apply': typeof AfterLoginApplyRoute
  '/certification': typeof AfterLoginCertificationRoute
  '/graduates-all': typeof AfterLoginGraduatesAllRoute
  '/guidelines-and-rules': typeof AfterLoginGuidelinesAndRulesRoute
  '/schedule': typeof AfterLoginScheduleRoute
  '/status': typeof AfterLoginStatusRoute
  '/thesis': typeof AfterLoginThesisRoute
  '/': typeof AfterLoginIndexRoute
  '/notices/$postId': typeof AfterLoginNoticesPostIdRoute
  '/notices/create': typeof AfterLoginNoticesCreateRoute
  '/notices': typeof AfterLoginNoticesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_afterLogin': typeof AfterLoginRouteWithChildren
  '/login': typeof LoginRoute
  '/_afterLogin/apply': typeof AfterLoginApplyRoute
  '/_afterLogin/certification': typeof AfterLoginCertificationRoute
  '/_afterLogin/graduates-all': typeof AfterLoginGraduatesAllRoute
  '/_afterLogin/guidelines-and-rules': typeof AfterLoginGuidelinesAndRulesRoute
  '/_afterLogin/schedule': typeof AfterLoginScheduleRoute
  '/_afterLogin/status': typeof AfterLoginStatusRoute
  '/_afterLogin/thesis': typeof AfterLoginThesisRoute
  '/_afterLogin/': typeof AfterLoginIndexRoute
  '/_afterLogin/notices/$postId': typeof AfterLoginNoticesPostIdRoute
  '/_afterLogin/notices/create': typeof AfterLoginNoticesCreateRoute
  '/_afterLogin/notices/': typeof AfterLoginNoticesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/apply'
    | '/certification'
    | '/graduates-all'
    | '/guidelines-and-rules'
    | '/schedule'
    | '/status'
    | '/thesis'
    | '/'
    | '/notices/$postId'
    | '/notices/create'
    | '/notices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/apply'
    | '/certification'
    | '/graduates-all'
    | '/guidelines-and-rules'
    | '/schedule'
    | '/status'
    | '/thesis'
    | '/'
    | '/notices/$postId'
    | '/notices/create'
    | '/notices'
  id:
    | '__root__'
    | '/_afterLogin'
    | '/login'
    | '/_afterLogin/apply'
    | '/_afterLogin/certification'
    | '/_afterLogin/graduates-all'
    | '/_afterLogin/guidelines-and-rules'
    | '/_afterLogin/schedule'
    | '/_afterLogin/status'
    | '/_afterLogin/thesis'
    | '/_afterLogin/'
    | '/_afterLogin/notices/$postId'
    | '/_afterLogin/notices/create'
    | '/_afterLogin/notices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AfterLoginRoute: typeof AfterLoginRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_afterLogin': {
      id: '/_afterLogin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AfterLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_afterLogin/': {
      id: '/_afterLogin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AfterLoginIndexRouteImport
      parentRoute: typeof AfterLoginRoute
    }
    '/_afterLogin/thesis': {
      id: '/_afterLogin/thesis'
      path: '/thesis'
      fullPath: '/thesis'
      preLoaderRoute: typeof AfterLoginThesisRouteImport
      parentRoute: typeof AfterLoginRoute
    }
    '/_afterLogin/status': {
      id: '/_afterLogin/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AfterLoginStatusRouteImport
      parentRoute: typeof AfterLoginRoute
    }
    '/_afterLogin/schedule': {
      id: '/_afterLogin/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AfterLoginScheduleRouteImport
      parentRoute: typeof AfterLoginRoute
    }
    '/_afterLogin/guidelines-and-rules': {
      id: '/_afterLogin/guidelines-and-rules'
      path: '/guidelines-and-rules'
      fullPath: '/guidelines-and-rules'
      preLoaderRoute: typeof AfterLoginGuidelinesAndRulesRouteImport
      parentRoute: typeof AfterLoginRoute
    }
    '/_afterLogin/graduates-all': {
      id: '/_afterLogin/graduates-all'
      path: '/graduates-all'
      fullPath: '/graduates-all'
      preLoaderRoute: typeof AfterLoginGraduatesAllRouteImport
      parentRoute: typeof AfterLoginRoute
    }
    '/_afterLogin/certification': {
      id: '/_afterLogin/certification'
      path: '/certification'
      fullPath: '/certification'
      preLoaderRoute: typeof AfterLoginCertificationRouteImport
      parentRoute: typeof AfterLoginRoute
    }
    '/_afterLogin/apply': {
      id: '/_afterLogin/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof AfterLoginApplyRouteImport
      parentRoute: typeof AfterLoginRoute
    }
    '/_afterLogin/notices/': {
      id: '/_afterLogin/notices/'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof AfterLoginNoticesIndexRouteImport
      parentRoute: typeof AfterLoginRoute
    }
    '/_afterLogin/notices/create': {
      id: '/_afterLogin/notices/create'
      path: '/notices/create'
      fullPath: '/notices/create'
      preLoaderRoute: typeof AfterLoginNoticesCreateRouteImport
      parentRoute: typeof AfterLoginRoute
    }
    '/_afterLogin/notices/$postId': {
      id: '/_afterLogin/notices/$postId'
      path: '/notices/$postId'
      fullPath: '/notices/$postId'
      preLoaderRoute: typeof AfterLoginNoticesPostIdRouteImport
      parentRoute: typeof AfterLoginRoute
    }
  }
}

interface AfterLoginRouteChildren {
  AfterLoginApplyRoute: typeof AfterLoginApplyRoute
  AfterLoginCertificationRoute: typeof AfterLoginCertificationRoute
  AfterLoginGraduatesAllRoute: typeof AfterLoginGraduatesAllRoute
  AfterLoginGuidelinesAndRulesRoute: typeof AfterLoginGuidelinesAndRulesRoute
  AfterLoginScheduleRoute: typeof AfterLoginScheduleRoute
  AfterLoginStatusRoute: typeof AfterLoginStatusRoute
  AfterLoginThesisRoute: typeof AfterLoginThesisRoute
  AfterLoginIndexRoute: typeof AfterLoginIndexRoute
  AfterLoginNoticesPostIdRoute: typeof AfterLoginNoticesPostIdRoute
  AfterLoginNoticesCreateRoute: typeof AfterLoginNoticesCreateRoute
  AfterLoginNoticesIndexRoute: typeof AfterLoginNoticesIndexRoute
}

const AfterLoginRouteChildren: AfterLoginRouteChildren = {
  AfterLoginApplyRoute: AfterLoginApplyRoute,
  AfterLoginCertificationRoute: AfterLoginCertificationRoute,
  AfterLoginGraduatesAllRoute: AfterLoginGraduatesAllRoute,
  AfterLoginGuidelinesAndRulesRoute: AfterLoginGuidelinesAndRulesRoute,
  AfterLoginScheduleRoute: AfterLoginScheduleRoute,
  AfterLoginStatusRoute: AfterLoginStatusRoute,
  AfterLoginThesisRoute: AfterLoginThesisRoute,
  AfterLoginIndexRoute: AfterLoginIndexRoute,
  AfterLoginNoticesPostIdRoute: AfterLoginNoticesPostIdRoute,
  AfterLoginNoticesCreateRoute: AfterLoginNoticesCreateRoute,
  AfterLoginNoticesIndexRoute: AfterLoginNoticesIndexRoute,
}

const AfterLoginRouteWithChildren = AfterLoginRoute._addFileChildren(
  AfterLoginRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AfterLoginRoute: AfterLoginRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
