/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AfterLoginRouteImport } from './routes/_afterLogin'
import { Route as AfterLoginIndexRouteImport } from './routes/_afterLogin/index'
import { Route as AfterLoginThesisRouteImport } from './routes/_afterLogin/thesis'
import { Route as AfterLoginStatusRouteImport } from './routes/_afterLogin/status'
import { Route as AfterLoginScheduleRouteImport } from './routes/_afterLogin/schedule'
import { Route as AfterLoginRulesRouteImport } from './routes/_afterLogin/rules'
import { Route as AfterLoginCertificationRouteImport } from './routes/_afterLogin/certification'
import { Route as AfterLoginApplyRouteImport } from './routes/_afterLogin/apply'
import { Route as AfterLoginAllRouteImport } from './routes/_afterLogin/all'
import { Route as AfterLoginNoticeIndexRouteImport } from './routes/_afterLogin/notice/index'
import { Route as AfterLoginNoticeCreateRouteImport } from './routes/_afterLogin/notice/create'
import { Route as AfterLoginNoticePostIdRouteImport } from './routes/_afterLogin/notice/$postId'
import { Route as rootRouteImport } from './routes/__root';
import { Route as LoginRouteImport } from './routes/login';
import { Route as AfterLoginRouteImport } from './routes/_afterLogin';
import { Route as AfterLoginIndexRouteImport } from './routes/_afterLogin/index';
import { Route as AfterLoginThesisRouteImport } from './routes/_afterLogin/thesis';
import { Route as AfterLoginStatusRouteImport } from './routes/_afterLogin/status';
import { Route as AfterLoginScheduleRouteImport } from './routes/_afterLogin/schedule';
import { Route as AfterLoginRulesRouteImport } from './routes/_afterLogin/rules';
import { Route as AfterLoginCertificationRouteImport } from './routes/_afterLogin/certification';
import { Route as AfterLoginApplyRouteImport } from './routes/_afterLogin/apply';
import { Route as AfterLoginAllRouteImport } from './routes/_afterLogin/all';
import { Route as AfterLoginNoticeIndexRouteImport } from './routes/_afterLogin/notice/index';
import { Route as AfterLoginNoticeCreateRouteImport } from './routes/_afterLogin/notice/create';
import { Route as AfterLoginNoticePostIdRouteImport } from './routes/_afterLogin/notice/$postId';

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const AfterLoginRoute = AfterLoginRouteImport.update({
  id: '/_afterLogin',
  getParentRoute: () => rootRouteImport,
} as any);
const AfterLoginIndexRoute = AfterLoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AfterLoginRoute,
} as any);
const AfterLoginThesisRoute = AfterLoginThesisRouteImport.update({
  id: '/thesis',
  path: '/thesis',
  getParentRoute: () => AfterLoginRoute,
} as any);
const AfterLoginStatusRoute = AfterLoginStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AfterLoginRoute,
} as any);
const AfterLoginScheduleRoute = AfterLoginScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AfterLoginRoute,
} as any);
const AfterLoginRulesRoute = AfterLoginRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AfterLoginRoute,
} as any);
const AfterLoginCertificationRoute = AfterLoginCertificationRouteImport.update({
  id: '/certification',
  path: '/certification',
  getParentRoute: () => AfterLoginRoute,
} as any);
const AfterLoginApplyRoute = AfterLoginApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => AfterLoginRoute,
} as any);
const AfterLoginAllRoute = AfterLoginAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => AfterLoginRoute,
} as any);
const AfterLoginNoticeIndexRoute = AfterLoginNoticeIndexRouteImport.update({
  id: '/notice/',
  path: '/notice/',
  getParentRoute: () => AfterLoginRoute,
} as any);
const AfterLoginNoticeCreateRoute = AfterLoginNoticeCreateRouteImport.update({
  id: '/notice/create',
  path: '/notice/create',
  getParentRoute: () => AfterLoginRoute,
} as any);
const AfterLoginNoticePostIdRoute = AfterLoginNoticePostIdRouteImport.update({
  id: '/notice/$postId',
  path: '/notice/$postId',
  getParentRoute: () => AfterLoginRoute,
} as any);

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/all': typeof AfterLoginAllRoute
  '/apply': typeof AfterLoginApplyRoute
  '/certification': typeof AfterLoginCertificationRoute
  '/rules': typeof AfterLoginRulesRoute
  '/schedule': typeof AfterLoginScheduleRoute
  '/status': typeof AfterLoginStatusRoute
  '/thesis': typeof AfterLoginThesisRoute
  '/': typeof AfterLoginIndexRoute
  '/notice/$postId': typeof AfterLoginNoticePostIdRoute
  '/notice/create': typeof AfterLoginNoticeCreateRoute
  '/notice': typeof AfterLoginNoticeIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/all': typeof AfterLoginAllRoute
  '/apply': typeof AfterLoginApplyRoute
  '/certification': typeof AfterLoginCertificationRoute
  '/rules': typeof AfterLoginRulesRoute
  '/schedule': typeof AfterLoginScheduleRoute
  '/status': typeof AfterLoginStatusRoute
  '/thesis': typeof AfterLoginThesisRoute
  '/': typeof AfterLoginIndexRoute
  '/notice/$postId': typeof AfterLoginNoticePostIdRoute
  '/notice/create': typeof AfterLoginNoticeCreateRoute
  '/notice': typeof AfterLoginNoticeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_afterLogin': typeof AfterLoginRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_afterLogin/all': typeof AfterLoginAllRoute
  '/_afterLogin/apply': typeof AfterLoginApplyRoute
  '/_afterLogin/certification': typeof AfterLoginCertificationRoute
  '/_afterLogin/rules': typeof AfterLoginRulesRoute
  '/_afterLogin/schedule': typeof AfterLoginScheduleRoute
  '/_afterLogin/status': typeof AfterLoginStatusRoute
  '/_afterLogin/thesis': typeof AfterLoginThesisRoute
  '/_afterLogin/': typeof AfterLoginIndexRoute
  '/_afterLogin/notice/$postId': typeof AfterLoginNoticePostIdRoute
  '/_afterLogin/notice/create': typeof AfterLoginNoticeCreateRoute
  '/_afterLogin/notice/': typeof AfterLoginNoticeIndexRoute
  '/login': typeof LoginRoute;
  '/all': typeof AfterLoginAllRoute;
  '/apply': typeof AfterLoginApplyRoute;
  '/certification': typeof AfterLoginCertificationRoute;
  '/rules': typeof AfterLoginRulesRoute;
  '/schedule': typeof AfterLoginScheduleRoute;
  '/status': typeof AfterLoginStatusRoute;
  '/thesis': typeof AfterLoginThesisRoute;
  '/': typeof AfterLoginIndexRoute;
  '/notice/$postId': typeof AfterLoginNoticePostIdRoute;
  '/notice/create': typeof AfterLoginNoticeCreateRoute;
  '/notice': typeof AfterLoginNoticeIndexRoute;
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute;
  '/all': typeof AfterLoginAllRoute;
  '/apply': typeof AfterLoginApplyRoute;
  '/certification': typeof AfterLoginCertificationRoute;
  '/rules': typeof AfterLoginRulesRoute;
  '/schedule': typeof AfterLoginScheduleRoute;
  '/status': typeof AfterLoginStatusRoute;
  '/thesis': typeof AfterLoginThesisRoute;
  '/': typeof AfterLoginIndexRoute;
  '/notice/$postId': typeof AfterLoginNoticePostIdRoute;
  '/notice/create': typeof AfterLoginNoticeCreateRoute;
  '/notice': typeof AfterLoginNoticeIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_afterLogin': typeof AfterLoginRouteWithChildren;
  '/login': typeof LoginRoute;
  '/_afterLogin/all': typeof AfterLoginAllRoute;
  '/_afterLogin/apply': typeof AfterLoginApplyRoute;
  '/_afterLogin/certification': typeof AfterLoginCertificationRoute;
  '/_afterLogin/rules': typeof AfterLoginRulesRoute;
  '/_afterLogin/schedule': typeof AfterLoginScheduleRoute;
  '/_afterLogin/status': typeof AfterLoginStatusRoute;
  '/_afterLogin/thesis': typeof AfterLoginThesisRoute;
  '/_afterLogin/': typeof AfterLoginIndexRoute;
  '/_afterLogin/notice/$postId': typeof AfterLoginNoticePostIdRoute;
  '/_afterLogin/notice/create': typeof AfterLoginNoticeCreateRoute;
  '/_afterLogin/notice/': typeof AfterLoginNoticeIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/login'
    | '/signup'
    | '/all'
    | '/apply'
    | '/certification'
    | '/rules'
    | '/schedule'
    | '/status'
    | '/thesis'
    | '/'
    | '/notice/$postId'
    | '/notice/create'
    | '/notice';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/login'
    | '/signup'
    | '/all'
    | '/apply'
    | '/certification'
    | '/rules'
    | '/schedule'
    | '/status'
    | '/thesis'
    | '/'
    | '/notice/$postId'
    | '/notice/create'
    | '/notice';
  id:
    | '__root__'
    | '/_afterLogin'
    | '/login'
    | '/signup'
    | '/_afterLogin/all'
    | '/_afterLogin/apply'
    | '/_afterLogin/certification'
    | '/_afterLogin/rules'
    | '/_afterLogin/schedule'
    | '/_afterLogin/status'
    | '/_afterLogin/thesis'
    | '/_afterLogin/'
    | '/_afterLogin/notice/$postId'
    | '/_afterLogin/notice/create'
    | '/_afterLogin/notice/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AfterLoginRoute: typeof AfterLoginRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_afterLogin': {
      id: '/_afterLogin';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof AfterLoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_afterLogin/': {
      id: '/_afterLogin/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof AfterLoginIndexRouteImport;
      parentRoute: typeof AfterLoginRoute;
    };
    '/_afterLogin/thesis': {
      id: '/_afterLogin/thesis';
      path: '/thesis';
      fullPath: '/thesis';
      preLoaderRoute: typeof AfterLoginThesisRouteImport;
      parentRoute: typeof AfterLoginRoute;
    };
    '/_afterLogin/status': {
      id: '/_afterLogin/status';
      path: '/status';
      fullPath: '/status';
      preLoaderRoute: typeof AfterLoginStatusRouteImport;
      parentRoute: typeof AfterLoginRoute;
    };
    '/_afterLogin/schedule': {
      id: '/_afterLogin/schedule';
      path: '/schedule';
      fullPath: '/schedule';
      preLoaderRoute: typeof AfterLoginScheduleRouteImport;
      parentRoute: typeof AfterLoginRoute;
    };
    '/_afterLogin/rules': {
      id: '/_afterLogin/rules';
      path: '/rules';
      fullPath: '/rules';
      preLoaderRoute: typeof AfterLoginRulesRouteImport;
      parentRoute: typeof AfterLoginRoute;
    };
    '/_afterLogin/certification': {
      id: '/_afterLogin/certification';
      path: '/certification';
      fullPath: '/certification';
      preLoaderRoute: typeof AfterLoginCertificationRouteImport;
      parentRoute: typeof AfterLoginRoute;
    };
    '/_afterLogin/apply': {
      id: '/_afterLogin/apply';
      path: '/apply';
      fullPath: '/apply';
      preLoaderRoute: typeof AfterLoginApplyRouteImport;
      parentRoute: typeof AfterLoginRoute;
    };
    '/_afterLogin/all': {
      id: '/_afterLogin/all';
      path: '/all';
      fullPath: '/all';
      preLoaderRoute: typeof AfterLoginAllRouteImport;
      parentRoute: typeof AfterLoginRoute;
    };
    '/_afterLogin/notice/': {
      id: '/_afterLogin/notice/';
      path: '/notice';
      fullPath: '/notice';
      preLoaderRoute: typeof AfterLoginNoticeIndexRouteImport;
      parentRoute: typeof AfterLoginRoute;
    };
    '/_afterLogin/notice/create': {
      id: '/_afterLogin/notice/create';
      path: '/notice/create';
      fullPath: '/notice/create';
      preLoaderRoute: typeof AfterLoginNoticeCreateRouteImport;
      parentRoute: typeof AfterLoginRoute;
    };
    '/_afterLogin/notice/$postId': {
      id: '/_afterLogin/notice/$postId';
      path: '/notice/$postId';
      fullPath: '/notice/$postId';
      preLoaderRoute: typeof AfterLoginNoticePostIdRouteImport;
      parentRoute: typeof AfterLoginRoute;
    };
  }
}

interface AfterLoginRouteChildren {
  AfterLoginAllRoute: typeof AfterLoginAllRoute;
  AfterLoginApplyRoute: typeof AfterLoginApplyRoute;
  AfterLoginCertificationRoute: typeof AfterLoginCertificationRoute;
  AfterLoginRulesRoute: typeof AfterLoginRulesRoute;
  AfterLoginScheduleRoute: typeof AfterLoginScheduleRoute;
  AfterLoginStatusRoute: typeof AfterLoginStatusRoute;
  AfterLoginThesisRoute: typeof AfterLoginThesisRoute;
  AfterLoginIndexRoute: typeof AfterLoginIndexRoute;
  AfterLoginNoticePostIdRoute: typeof AfterLoginNoticePostIdRoute;
  AfterLoginNoticeCreateRoute: typeof AfterLoginNoticeCreateRoute;
  AfterLoginNoticeIndexRoute: typeof AfterLoginNoticeIndexRoute;
}

const AfterLoginRouteChildren: AfterLoginRouteChildren = {
  AfterLoginAllRoute: AfterLoginAllRoute,
  AfterLoginApplyRoute: AfterLoginApplyRoute,
  AfterLoginCertificationRoute: AfterLoginCertificationRoute,
  AfterLoginRulesRoute: AfterLoginRulesRoute,
  AfterLoginScheduleRoute: AfterLoginScheduleRoute,
  AfterLoginStatusRoute: AfterLoginStatusRoute,
  AfterLoginThesisRoute: AfterLoginThesisRoute,
  AfterLoginIndexRoute: AfterLoginIndexRoute,
  AfterLoginNoticePostIdRoute: AfterLoginNoticePostIdRoute,
  AfterLoginNoticeCreateRoute: AfterLoginNoticeCreateRoute,
  AfterLoginNoticeIndexRoute: AfterLoginNoticeIndexRoute,
};

const AfterLoginRouteWithChildren = AfterLoginRoute._addFileChildren(
  AfterLoginRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  AfterLoginRoute: AfterLoginRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
