name: CI

env:
  HUSKY: 0

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Pipelines:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ['lint', 'build']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install

      - name: create dotenv
        run: |
          touch ./apps/community/.env
          echo "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL" >> ./apps/community/.env
          echo "NEXT_PUBLIC_AUTH_API_URL=$NEXT_PUBLIC_AUTH_API_URL" >> ./apps/community/.env
        env: 
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_AUTH_API_URL: ${{ secrets.NEXT_PUBLIC_AUTH_API_URL }}
          
          
      - name: Run commands
        run: pnpm ${{ matrix.command }}

      
